spring:
  application:
    name: anything
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${spring.profiles.active:default}
  security:
    enabled: false

logging:
  level:
    org.springframework.boot.actuate: DEBUG
    org.springframework.boot.actuate.endpoint.web.servlet: DEBUG
    io.micrometer: DEBUG
    io.micrometer.prometheus: DEBUG

